---
title: "Class 06 Homework"
author: "Claire Chapman"
date: "10/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bio3d)
```

# Can you improve this code?
```{r}
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

## Fixing copy/paste errors
```{r}
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```
## Simplifying the core code snippet
```{r}
x <- read.pdb("4AKE")
x.chainA <- trim.pdb(x, chain = "A", elety = "CA")
x.atomb <- x.chainA$atom$b
plotb3(x.atomb, sse = x.chainA, typ = "l", ylab = "Bfactor")
```
## Making a function out of the simplified snippet
```{r}
protein <- function(file) {
  x <- read.pdb(file)
  x.chainA <- trim.pdb(x, chain="A", elety="CA")
  x.atomb <- x.chainA$atom$b
  plotb3(x.atomb, sse=x.chainA, typ = "l", ylab = "Bfactor")
}
```

## Testing the new function 
```{r}
protein("4AKE")
```
```{r}
protein("1AKE")
```
```{r}
protein("1E4Y")
```

## Adding annotations
First exploring plotb3() to understand the plot better
```{r}
help(plotb3)
```

Annotations
```{r}
#' Line Plot of Protein Drug Interactions
#'
#' @param x A .pdb file
#'
#' @return plot of chain A of a protein drug interaction
#' @export
#'
#' @examples
protein <- function(file) {
  x <- read.pdb(file)
  x.chainA <- trim.pdb(x, chain="A", elety="CA")
  x.atomb <- x.chainA$atom$b
  plotb3(x.atomb, sse=x.chainA, typ = "l", ylab = "Bfactor")
}

protein("4AKE")
```

